"""
Django settings for mydjangoprojects project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r5fe!lm$@$uc^)i5zk1!0qcj)e0#_tuz(h%lfjzfwk2of5)3dg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# DEBUG = False
#
# ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'commodity',
    'user',
)

MIDDLEWARE_CLASSES = (
    # 'mydjangoprojects.middleware.FilterIPMiddleware',
    # 'mydjangoprojects.middleware.ExceotionMiddleware',


    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mydjangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #设置模板路径
        'DIRS': [os.path.join(BASE_DIR,'tempaltes')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mydjangoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
#配置连接mysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':('dailyfresh'),
        'USER': 'root',
        'PASSWORD': 'syg',
        'HOST': '192.168.12.164',
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/


LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
#配置静态文件
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
#设置字体
FONT_STYLE='/usr/share/fonts/truetype/freefont/FreeSerifItalic.ttf'
#禁止的IP
FORBIDDEN_IPS=[
    '192.168.12.166',
    # '192.168.12.178'
    '192.168.12.133',
    '192.168.12.134',
]
#上传文件储存的路径
MEDIA_ROOT=os.path.join(BASE_DIR,'static/media')


#session 交给redis管理
# SESSION_ENGINE = 'redis_sessions.session'
# SESSION_REDIS_HOST = '192.168.12.164'
# SESSION_REDIS_PORT = 6379
# SESSION_REDIS_DB = 15
# SESSION_REDIS_PASSWORD = ''
# SESSION_REDIS_PREFIX = 'session'

AUTH_USER_MODEL='user.User'

#发送邮件配置
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.163.com'
EMAIL_PORT='25'
EMAIL_HOST_USER='18336233108@163.com'
EMAIL_HOST_PASSWORD='syg147258369'
EMAIL_FORM='天天生鲜<18336233108@163.com'
